export const countryCodes = [
  { code: '+93', value: 'Afghanistan' },
  { code: '+355', value: 'Albania' },
  { code: '+213', value: 'Algeria' },
  { code: '+376', value: 'Andorra' },
  { code: '+244', value: 'Angola' },
  { code: '+1-268', value: 'Antigua and Barbuda' },
  { code: '+54', value: 'Argentina' },
  { code: '+374', value: 'Armenia' },
  { code: '+61', value: 'Australia' },
  { code: '+43', value: 'Austria' },
  { code: '+994', value: 'Azerbaijan' },
  { code: '+1-242', value: 'Bahamas' },
  { code: '+973', value: 'Bahrain' },
  { code: '+880', value: 'Bangladesh' },
  { code: '+1-246', value: 'Barbados' },
  { code: '+375', value: 'Belarus' },
  { code: '+32', value: 'Belgium' },
  { code: '+501', value: 'Belize' },
  { code: '+229', value: 'Benin' },
  { code: '+975', value: 'Bhutan' },
  { code: '+591', value: 'Bolivia' },
  { code: '+387', value: 'Bosnia and Herzegovina' },
  { code: '+267', value: 'Botswana' },
  { code: '+55', value: 'Brazil' },
  { code: '+673', value: 'Brunei' },
  { code: '+359', value: 'Bulgaria' },
  { code: '+226', value: 'Burkina Faso' },
  { code: '+257', value: 'Burundi' },
  { code: '+855', value: 'Cambodia' },
  { code: '+237', value: 'Cameroon' },
  { code: '+1', value: 'Canada' },
  { code: '+238', value: 'Cape Verde' },
  { code: '+236', value: 'Central African Republic' },
  { code: '+235', value: 'Chad' },
  { code: '+56', value: 'Chile' },
  { code: '+86', value: 'China' },
  { code: '+57', value: 'Colombia' },
  { code: '+269', value: 'Comoros' },
  { code: '+506', value: 'Costa Rica' },
  { code: '+385', value: 'Croatia' },
  { code: '+53', value: 'Cuba' },
  { code: '+357', value: 'Cyprus' },
  { code: '+420', value: 'Czech Republic' },
  { code: '+243', value: 'Democratic Republic of the Congo' },
  { code: '+45', value: 'Denmark' },
  { code: '+253', value: 'Djibouti' },
  { code: '+1-767', value: 'Dominica' },
  { code: '+1-809 and +1-829', value: 'Dominican Republic' },
  { code: '+670', value: 'East Timor' },
  { code: '+593', value: 'Ecuador' },
  { code: '+20', value: 'Egypt' },
  { code: '+503', value: 'El Salvador' },
  { code: '+240', value: 'Equatorial Guinea' },
  { code: '+291', value: 'Eritrea' },
  { code: '+372', value: 'Estonia' },
  { code: '+251', value: 'Ethiopia' },
  { code: '+679', value: 'Fiji' },
  { code: '+358', value: 'Finland' },
  { code: '+33', value: 'France' },
  { code: '+241', value: 'Gabon' },
  { code: '+220', value: 'Gambia' },
  { code: '+995', value: 'Georgia' },
  { code: '+49', value: 'Germany' },
  { code: '+233', value: 'Ghana' },
  { code: '+30', value: 'Greece' },
  { code: '+1-473', value: 'Grenada' },
  { code: '+502', value: 'Guatemala' },
  { code: '+224', value: 'Guinea' },
  { code: '+245', value: 'Guinea-Bissau' },
  { code: '+592', value: 'Guyana' },
  { code: '+509', value: 'Haiti' },
  { code: '+504', value: 'Honduras' },
  { code: '+36', value: 'Hungary' },
  { code: '+354', value: 'Iceland' },
  { code: '+91', value: 'India' },
  { code: '+62', value: 'Indonesia' },
  { code: '+98', value: 'Iran' },
  { code: '+964', value: 'Iraq' },
  { code: '+353', value: 'Ireland' },
  { code: '+972', value: 'Israel' },
  { code: '+39', value: 'Italy' },
  { code: '+225', value: 'Ivory Coast' },
  { code: '+1-876', value: 'Jamaica' },
  { code: '+81', value: 'Japan' },
  { code: '+962', value: 'Jordan' },
  { code: '+7', value: 'Kazakhstan' },
  { code: '+254', value: 'Kenya' },
  { code: '+686', value: 'Kiribati' },
  { code: '+383', value: 'Kosovo' },
  { code: '+965', value: 'Kuwait' },
  { code: '+996', value: 'Kyrgyzstan' },
  { code: '+856', value: 'Laos' },
  { code: '+371', value: 'Latvia' },
  { code: '+961', value: 'Lebanon' },
  { code: '+266', value: 'Lesotho' },
  { code: '+231', value: 'Liberia' },
  { code: '+218', value: 'Libya' },
  { code: '+423', value: 'Liechtenstein' },
  { code: '+370', value: 'Lithuania' },
  { code: '+352', value: 'Luxembourg' },
  { code: '+389', value: 'Macedonia' },
  { code: '+261', value: 'Madagascar' },
  { code: '+265', value: 'Malawi' },
  { code: '+60', value: 'Malaysia' },
  { code: '+960', value: 'Maldives' },
  { code: '+223', value: 'Mali' },
  { code: '+356', value: 'Malta' },
  { code: '+692', value: 'Marshall Islands' },
  { code: '+222', value: 'Mauritania' },
  { code: '+230', value: 'Mauritius' },
  { code: '+262', value: 'Mayotte' },
  { code: '+52', value: 'Mexico' },
  { code: '+691', value: 'Micronesia' },
  { code: '+373', value: 'Moldova' },
  { code: '+377', value: 'Monaco' },
  { code: '+976', value: 'Mongolia' },
  { code: '+382', value: 'Montenegro' },
  { code: '+212', value: 'Morocco' },
  { code: '+258', value: 'Mozambique' },
  { code: '+95', value: 'Myanmar' },
  { code: '+264', value: 'Namibia' },
  { code: '+674', value: 'Nauru' },
  { code: '+977', value: 'Nepal' },
  { code: '+31', value: 'Netherlands' },
  { code: '+64', value: 'New Zealand' },
  { code: '+505', value: 'Nicaragua' },
  { code: '+227', value: 'Niger' },
  { code: '+234', value: 'Nigeria' },
  { code: '+850', value: 'North Korea' },
  { code: '+47', value: 'Norway' },
  { code: '+968', value: 'Oman' },
  { code: '+92', value: 'Pakistan' },
  { code: '+680', value: 'Palau' },
  { code: '+970', value: 'Palestine' },
  { code: '+507', value: 'Panama' },
  { code: '+675', value: 'Papua New Guinea' },
  { code: '+595', value: 'Paraguay' },
  { code: '+51', value: 'Peru' },
  { code: '+63', value: 'Philippines' },
  { code: '+48', value: 'Poland' },
  { code: '+351', value: 'Portugal' },
  { code: '+974', value: 'Qatar' },
  { code: '+242', value: 'Republic of the Congo' },
  { code: '+40', value: 'Romania' },
  { code: '+7', value: 'Russia' },
  { code: '+250', value: 'Rwanda' },
  { code: '+290', value: 'Saint Helena' },
  { code: '+1-869', value: 'Saint Kitts and Nevis' },
  { code: '+1-758', value: 'Saint Lucia' },
  { code: '+508', value: 'Saint Pierre and Miquelon' },
  { code: '+1-784', value: 'Saint Vincent and the Grenadines' },
  { code: '+685', value: 'Samoa' },
  { code: '+378', value: 'San Marino' },
  { code: '+239', value: 'Sao Tome and Principe' },
  { code: '+966', value: 'Saudi Arabia' },
  { code: '+221', value: 'Senegal' },
  { code: '+381', value: 'Serbia' },
  { code: '+248', value: 'Seychelles' },
  { code: '+232', value: 'Sierra Leone' },
  { code: '+65', value: 'Singapore' },
  { code: '+421', value: 'Slovakia' },
  { code: '+386', value: 'Slovenia' },
  { code: '+677', value: 'Solomon Islands' },
  { code: '+252', value: 'Somalia' },
  { code: '+27', value: 'South Africa' },
  { code: '+82', value: 'South Korea' },
  { code: '+211', value: 'South Sudan' },
  { code: '+34', value: 'Spain' },
  { code: '+94', value: 'Sri Lanka' },
  { code: '+249', value: 'Sudan' },
  { code: '+597', value: 'Suriname' },
  { code: '+268', value: 'Swaziland' },
  { code: '+46', value: 'Sweden' },
  { code: '+41', value: 'Switzerland' },
  { code: '+963', value: 'Syria' },
  { code: '+886', value: 'Taiwan' },
  { code: '+992', value: 'Tajikistan' },
  { code: '+255', value: 'Tanzania' },
  { code: '+66', value: 'Thailand' },
  { code: '+228', value: 'Togo' },
  { code: '+690', value: 'Tokelau' },
  { code: '+676', value: 'Tonga' },
  { code: '+1-868', value: 'Trinidad and Tobago' },
  { code: '+216', value: 'Tunisia' },
  { code: '+90', value: 'Turkey' },
  { code: '+993', value: 'Turkmenistan' },
  { code: '+688', value: 'Tuvalu' },
  { code: '+256', value: 'Uganda' },
  { code: '+380', value: 'Ukraine' },
  { code: '+971', value: 'United Arab Emirates' },
  { code: '+44', value: 'United Kingdom' },
  { code: '+1', value: 'United States' },
  { code: '+598', value: 'Uruguay' },
  { code: '+998', value: 'Uzbekistan' },
  { code: '+678', value: 'Vanuatu' },
  { code: '+379', value: 'Vatican City' },
  { code: '+58', value: 'Venezuela' },
  { code: '+84', value: 'Vietnam' },
  { code: '+681', value: 'Wallis and Futuna' },
  { code: '+967', value: 'Yemen' },
  { code: '+260', value: 'Zambia' },
  { code: '+263', value: 'Zimbabwe' },
];
